### PR TITLE
Use bool for long_strip field in chapter struct, fixes #5

### LINKED ISSUE #5: cannot unmarshal bool into Go struct field Chapter.long_strip of type int
Mangadex chapter api could return a bool or int for `long_strip` field.

### PR DESCRIPTION
**Pull request by Girbons**
This PR solves #5.

### CODE REVIEW

**Comment by bake** [comment]
Hi, thank you again for the contribution!

I think we could change the field to a boolean. The [example in `testdata`](https://github.com/bake/mangadex/blob/master/testdata/50a617260dabf869d4635164580fd061079ee1ba25c683c1d5b64aa9d5286df4) returned a `0` before but it seems to have [changed to `false`](https://mangadex.org/api/?type=chapter&id=517244). The latest released chapters also only contain `true` or `false` (or `null` in case the manga is restricted).

What do you think? Do you have an example where it still uses a number?

**Comment by Girbons** [comment]
> I think we could change the field to a boolean

I tried at first, but it doesn't work for all the chapters.

>  Do you have an example where it still uses a number?

The example is this [chapter](https://mangadex.org/api/?type=chapter&id=517244) which returns `0` in tests.

```could not unmarshal chapter 517244: json: cannot unmarshal number into Go struct field Chapter.long_strip of type bool```

**Comment by bake** [comment]
When I open the URL in the browser I get `false`. Are you using `go test`? If so, did you delete the files in `testdata`?

**Comment by Girbons** [comment]
>  If so, did you delete the files in testdata

My bad, I completely missed that part, now it all makes sense. We can indeed use a boolean!

**Comment by bake** [comment]
Great, thank you!

**Pull request merged**
